project_id = "feblgdfxkuegmjqsdycp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.notify-ghl]
    verify_jwt = false
  [functions.check-trial-ending]
    verify_jwt = false
  [functions.verify-apple-receipt]
    verify_jwt = false
